// GENERATED by publications/build_pubs.py - do not edit by hand.
window.PUBS_META = {
  "labs": [
    {
      "id": "feilong",
      "name": "Feilong Ma",
      "n": 21
    }
  ],
  "topics": [
    {
      "id": "hyperalignment",
      "label": "Hyperalignment",
      "group": "Methods",
      "n": 18
    },
    {
      "id": "individual-differences",
      "label": "Individual differences",
      "group": "Themes",
      "n": 12
    },
    {
      "id": "naturalistic",
      "label": "Naturalistic stimuli",
      "group": "Domains",
      "n": 14
    },
    {
      "id": "brain-templates",
      "label": "Brain templates",
      "group": "Methods",
      "n": 2
    },
    {
      "id": "artificial-intelligence",
      "label": "Artificial intelligence",
      "group": "Domains",
      "n": 4
    },
    {
      "id": "open-datasets",
      "label": "Open datasets",
      "group": "Methods",
      "n": 2
    },
    {
      "id": "development",
      "label": "Development",
      "group": "Themes",
      "n": 2
    },
    {
      "id": "face-perception",
      "label": "Face perception",
      "group": "Domains",
      "n": 4
    },
    {
      "id": "mvpa",
      "label": "MVPA/decoding",
      "group": "Methods",
      "n": 12
    },
    {
      "id": "representational-geometry",
      "label": "Representational geometry",
      "group": "Domains",
      "n": 6
    },
    {
      "id": "functional-connectivity",
      "label": "Functional connectivity",
      "group": "Domains",
      "n": 9
    },
    {
      "id": "encoding-models",
      "label": "Encoding models",
      "group": "Methods",
      "n": 3
    },
    {
      "id": "morphometry",
      "label": "Morphometry",
      "group": "Domains",
      "n": 1
    },
    {
      "id": "monkey-fmri",
      "label": "Monkey fMRI",
      "group": "Domains",
      "n": 1
    }
  ],
  "total": 21,
  "categories_n": {
    "empirical": 17,
    "review": 3,
    "data": 2
  },
  "n_key": 11
};
